# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('checkout', '0004_remove_creditcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='login.User'),
        ),
    ]
