# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_creditcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='last_four',
            field=models.CharField(default=7890, max_length=10),
            preserve_default=False,
        ),
    ]
