# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
