# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='primary_image',
        ),
    ]
