# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170201_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(default='images/None/no-img.jpg', null=True, upload_to='apps/home/static/home/images/'),
        ),
    ]
