# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('home', '0002_auto_20170202_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='login.User'),
            preserve_default=False,
        ),
    ]
