# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170201_1310'),
        ('home', '0003_auto_20170201_1049'),
        ('home', '0003_auto_20170201_1308'),
    ]

    operations = [
    ]
