# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_purchases', to='home.Order'),
        ),
    ]
