# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170130_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='home.Product')),
                ('spec_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_with_spec', to='home.SpecificationCategories')),
            ],
        ),
        migrations.RemoveField(
            model_name='spec',
            name='product',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='product',
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='home.Product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='apps/home/static/images/'),
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
    ]
