# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170130_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='home.Product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='apps/home/static/home/images/'),
        ),
    ]
